export const CREATE_CARD = "CREATE_CARD";
export const DELETE_CARD = "DELETE_CARD";
export const UPDATE_CARD = "UPDATE_CARD";
export const GET_ALL_CARDS = "GET_ALL_CARDS";
export const GET_CARD_BY_ID = "GET_CARD_BY_ID";
// export const CREATE_CARD = "CREATE_CARD";
export const AUTH = "AUTH";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
